name: Mental Health Assistant AMP
description: A mental health assistant using Cohere, FAISS, and LangChain to provide information and tips for overcoming mental health issues.
author: Your Name
specification_version: 1.0
prototype_version: 1.0
date: "2024-10-09"

environment_variables:
  COHERE_API_KEY:
    default: "996fB69PNLQjAiH4N2fnmTl4ccii91iz2Xr4mTfE"
    description: "API key for accessing the Cohere LLM."
    required: true

  SERP_API_KEY:
    default : "f39f64a7fef852a21486840761f31b9288a3f24c4e0689c40c16bff722daf5fb"
    description: "API key for assessing google scolar."
    required: true 
    

runtimes:
  - editor: Workbench
    kernel: Python 3.10
    edition: Standard

tasks:

  # Step 1: Install dependencies for the project
  - type: run_session
    name: Install Dependencies
    script: 0_session_install_dependencies/install-dependencies.py
    short_summary: "Install the necessary dependencies like LangChain, FAISS, Cohere, etc."
    kernel: python3
    cpu: 2
    memory: 4

  # Step 2: Run the job script to process and clean the data
  - type: create_job
    name: Process and Clean Data
    entity_label: process_clean_data
    script: job.py
    cpu: 2
    memory: 4
    short_summary: "Run the job to extract, load, clean the mental health data."
    environment:
      TASK_TYPE: "DATA_PROCESSING"

  # Step 3: Run the preprocessing script to generate embeddings and store in FAISS
  - type: create_job
    name: Preprocess Data and Create FAISS
    entity_label: preprocess_faiss
    script:preprocess.py
    cpu: 2
    memory: 4
    short_summary: "Generate embeddings and store the processed mental health data in FAISS."
    environment:
      TASK_TYPE: "EMBEDDING_PROCESS"

  # Step 4: Run the main.py file to initialize tools and agent, and handle user queries
  - type: run_session
    name: Run Mental Health Assistant
    script: main.py
    kernel: python3
    cpu: 4
    memory: 8
    short_summary: "Run the Mental Health Assistant to respond to user queries."
    environment_variables:
      TASK_TYPE: "RUN_AGENT"
  
  # Optional: Deploy the Streamlit app as a service
  - type: start_application
    name: Mental Health Assistant Web App
    short_summary: "Start the web interface for querying mental health-related information."
    long_summary: "This app uses Cohere LLM, FAISS vector search, and other tools to provide users with information related to mental health."
    subdomain: mental-health-assistant
    script: main.py
    environment_variables:
      TASK_TYPE: "START_APPLICATION"
    cpu: 4
    memory: 8
